### ISSUE TITLE
DEBUG:pyflume:Poorly formatted Access Token, fetching token using _creds

### ISSUE THREAD

**Issue by anthonystabile** [ChrisMandich/PyFlume#16]
Greetings Chris,

First off, thank you for writing this package!!! 

I am testing PyFlume tonight and ran into this error.   

DEBUG:pyflume:Poorly formatted Access Token, fetching token using _creds

Your thoughts on this are greatly appreciated.   Thanks!  - Anthony

**UPDATE:  I was able to come up with a workaround to this issue by performing a base64 decode on the payload (the second segment of self._token['access_token']) and JSON loading it into self._decoded_token.**

**jwt.exceptions.DecodeError** is being thrown from this line:
 
  __self._decoded_token = jwt.decode(self._token['access_token'], verify=False)

My token is getting successfully returned using this test page -> https://flumetech.readme.io/reference#get-tokens-1

I have used an online JWT decoder and successfully decoded the token.  I have confirmed that pyFlume is getting this token value from flume.log:

DEBUG:pyflume:Token file does not exist, fetching token using _creds
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.flumetech.com:443
DEBUG:urllib3.connectionpool:https://api.flumetech.com:443 "POST /oauth/token HTTP/1.1" 200 None
DEBUG:pyflume:Token Payload: {'grant_type': 'password', 'client_id': 'scrubbed', 'client_secret': 'scrubbed', 'username': 'scrubbed@scrubbed.com', 'password': 'scrubbed'}
DEBUG:pyflume:Token Response: {"success":true,"code":602,"message":"Request OK","http_code":200,"http_message":"OK","detailed":null,"data":[{"token_type":"bearer","access_token":"scrubbed","expires_in":604800,"refresh_token":"scrubbed"}],"count":1,"pagination":null}
DEBUG:pyflume:Poorly formatted Access Token, fetching token using _creds 

*** Data scrubbed

Side note:  When this occurs, due to the recursive call in the exception handling, this failure repeats infinitely up until the http response 429 - Too Many Requests kicks in.   

Python 3.6.5

Package      Version
------------ ---------
certifi      2020.12.5
cffi         1.14.5
chardet      4.0.0
cryptography 3.2.1
idna         2.10
pip          21.0.1
pycparser    2.20
PyFlume      0.6.2
PyJWT        2.0.1
pytz         2021.1
ratelimit    2.2.1
requests     2.25.1
setuptools   53.0.0
six          1.15.0
urllib3      1.26.3

**Comment by jimboca** [comment]
Thanks for posting this, I use this as well for integration with ISY. Any idea why this happens for some users but not all?

**Comment by kpnobvious** [comment]
I too am having this issue

**Comment by anthonystabile** [comment]
Until the package is updated I am sharing my workaround.   Within the package __init__.py file locate the following line

            LOGGER.debug('Poorly formatted Access Token, fetching token using _creds')

Comment out the recursive call 

            #self.fetch_token()
 
and insert this code after that point within the exception block. 

            tsplit = self._token['access_token'].split('.')
            # Extract payload from second part of token
            payload = str(tsplit[1])
            # add padding if needed:
            lens = len(payload)
            lenx = lens % 4 if lens % 4 else 4
            payload += str(b'=' * (4 - lenx))
            # Standard Base64 Decoding
            import base64
            decodedBytes = base64.b64decode(payload)
            decodedStr = str(decodedBytes, "utf-8")
            lenfinal = len(decodedStr)
            self._decoded_token = json.loads(decodedStr[:lenfinal - 1])

I had to add padding to perform the base64 decode, your mileage may vary.

**Comment by ChrisMandich** [comment]
Apologize as I have missed this notification. I'll work on getting this package updated with a fix over the next week. Thank you for your patience.

**Comment by ChrisMandich** [comment]
@anthonystabile, This issue looks to be related to PyJWT version. 
- 1.7.1 - Success
- 2.0.0 - Error received
- 2.0.1 - Error received
In the short-term i recommend testing with v1.7.1 as I look for a fix for 2.0.1 and update the package to include the required version number for dependencies.

**Comment by ChrisMandich** [comment]
Give this guy a try: https://pypi.org/project/PyFlume/0.6.4/

**Comment by jimboca** [comment]
Yes, that fixed it. Thank you!
