### ISSUE TITLE
High flow seems to have moved into usage-alerts

### ISSUE THREAD

**Issue by jeeftor** [ChrisMandich/PyFlume#26]
https://flumetech.readme.io/reference/fetch-user-usage-alerts

I used to get High Flow under notifications - I think it may have moved to:

https://api.flumewater.com/users/{user_id}/usage-alerts

**Comment by dorfman** [comment]
Hi there,

High Flow notifications have not been moved from `/notifications` to `/usage-alerts`; notifications are representative of what you're notified of via email or push notifications. Usage Alerts are technically a subset of Notifications. Every time a usage alert Notification is triggered, a Usage Alert is created. Notifications can be cleared/deleted. A Usage Alert will remain even if the Notification is deleted.

**Comment by jeeftor** [comment]
On my flume I'm getting high flow emails that are NOT showing up (any longer) under the notification endpoint. They only seem to be coming across the usage alert endpoint

**Comment by dorfman** [comment]
Message Flume's support and ask for Henry. I'll take a look at why your notifications aren't showing up properly.
